# Generated by Django 4.1.7 on 2023-02-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='created',
        ),
    ]
