# Generated by Django 4.1.7 on 2023-03-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_create_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
