# Generated by Django 4.1.7 on 2023-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_task_task_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
